[package]
name = "hyperbolic_graph_generator"
version = "0.1.0"
description = "Create different types of hyperbolic graphs."
authors = ["Moritz Warning <moritzwarning@web.de>"]
edition = "2018"

[dependencies]
GSL = "1.1.0"
log = "0.4.6"
